//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RheinBrucke {
    
    
    public partial class Merry_Christmas_and_Happy_New_Year_2017 {
    }
}
