//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RheinBrucke.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailRequest
    {
        public int EmailRequestID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Companyname { get; set; }
        public string Message { get; set; }
        public Nullable<int> EmailTypeID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ContactUsUrl { get; set; }
        public string Services { get; set; }
    
        public virtual EmailType EmailType { get; set; }
        public virtual EmailType EmailType1 { get; set; }
        public virtual EmailType EmailType2 { get; set; }
    }
}
