//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RheinBrucke.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailType
    {
        public EmailType()
        {
            this.EmailRequests = new HashSet<EmailRequest>();
            this.EmailRequests1 = new HashSet<EmailRequest>();
            this.EmailRequests2 = new HashSet<EmailRequest>();
        }
    
        public int EmailTypeID { get; set; }
        public string EmailTypeName { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual ICollection<EmailRequest> EmailRequests { get; set; }
        public virtual ICollection<EmailRequest> EmailRequests1 { get; set; }
        public virtual ICollection<EmailRequest> EmailRequests2 { get; set; }
    }
}
