//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RheinBrucke.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadSquareLog
    {
        public int LogId { get; set; }
        public Nullable<System.Guid> FormPID { get; set; }
        public string FormStatus { get; set; }
        public string FormMsg { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Company { get; set; }
        public string ServiceType { get; set; }
        public string FormAction { get; set; }
    }
}
