//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RheinBrucke.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsEvent
    {
        public int NewsAndEventsID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ThumbnailImage { get; set; }
        public string NewsImage { get; set; }
        public string MetaTagDescription { get; set; }
        public string MetaTagKeyword { get; set; }
        public Nullable<System.DateTime> NewsEventsDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> ThumbnailPositionLeft { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UrlDetails { get; set; }
    }
}
