//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RheinBrucke.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RheinBruckeDevEntities : DbContext
    {
        public RheinBruckeDevEntities()
            : base("name=RheinBruckeDevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<EmailRequest> EmailRequests { get; set; }
        public DbSet<EmailType> EmailTypes { get; set; }
        public DbSet<JobApplication> JobApplications { get; set; }
        public DbSet<JobList> JobLists { get; set; }
        public DbSet<LandingPage> LandingPages { get; set; }
        public DbSet<MailSetting> MailSettings { get; set; }
        public DbSet<NewsEvent> NewsEvents { get; set; }
        public DbSet<Testimonial> Testimonials { get; set; }
        public DbSet<Brochure> Brochures { get; set; }
        public DbSet<CaseStudy> CaseStudies { get; set; }
        public DbSet<WhitePaper> WhitePapers { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
        public DbSet<RICNew> RICNews { get; set; }
        public DbSet<FactSheet> FactSheets { get; set; }
        public DbSet<LeadSquareLog> LeadSquareLogs { get; set; }
        public DbSet<WebinarsList> WebinarsLists { get; set; }
        public DbSet<WebinarsRecording> WebinarsRecordings { get; set; }
    }
}
