//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RheinBrucke.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public int UserId { get; set; }
        public string UserRole1 { get; set; }
        public string EmailId { get; set; }
        public string Department { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Password { get; set; }
    }
}
