//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RheinBrucke.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebinarsList
    {
        public int WebinarId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string TakeAway { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> WebinarDate { get; set; }
        public string Speaker1 { get; set; }
        public string Speaker1Designation { get; set; }
        public string Speaker2 { get; set; }
        public string Speaker2Designation { get; set; }
        public string Speaker3 { get; set; }
        public string Speaker3Designation { get; set; }
        public string Speaker4 { get; set; }
        public string Speaker4Designation { get; set; }
        public string Moderator1 { get; set; }
        public string Moderator1Designation { get; set; }
        public string Moderator2 { get; set; }
        public string Moderator2Designation { get; set; }
        public string Timings { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string WebinarURL { get; set; }
        public string Category { get; set; }
        public string FilterName { get; set; }
    }
}
