//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RheinBrucke.Solutions.EnterpriseServicesAndSolutions.EPICOR
{


    public partial class Epicor_for_energy_utility
    {
    }
}
